import { StyleSheet } from "react-native";
export default StyleSheet.create({
    container:{
        backgroundColor:'#f78f3f',
        margin:10,
        padding:10,
        borderRadius:10,
        elevation:8,
        flexDirection:'row'
    },
    image:{
        width:50,
        height:50,
        borderRadius:5
    },
    modal:{
        justifyContent:'center',
        alignItems:'center'
    },
    modal_container:{
        width:300,
        height:200,
        backgroundColor:'white',
       alignItems:'center',
       justifyContent:'center',
       borderRadius:16,
       elevation:10

    },
    modal_image:{
        width:300,
        height:80,
        marginBottom:20,
        position:'absolute',
        right:0,
        top:30
    },
    buttons:{},
    marvel_image:{
        width:300,
        height:80
    },
    remove_container:{

    },
    body_container:{
        backgroundColor:'#518cca',
        height:120,
        width:'100%',
        borderBottomLeftRadius:16,
        borderBottomRightRadius:16
       
    },
    header_text:{
        color:'white',
        marginTop:20,
        alignSelf:'center'
    },
    ok_text:{
        color:'black'
    },
    ok_container:{
        backgroundColor:'white',
        marginTop:20,
        width:80,
        alignItems:'center',
        alignSelf:'center',
        marginRight:14,
        borderRadius:8,
        elevation:10
    }
})